### ISSUE TITLE
Possible to update for iOS 12.2 +?

### ISSUE THREAD

**Issue by technaustin** [fecaleagle/fecaleagle.github.io#4]
With the recent news of a 12.2 Jailbreak, I'm sure the community could really use this. Thank you for your efforts.

**Comment by fecaleagle** [comment]
It's trivial to make a pull request, and I'll gladly accept them.  In any case, updated through 12.3.2

https://github.com/fecaleagle/fecaleagle.github.io/commit/aaf18d956f27d7ba6e861728ad18165bf90eaef0#diff-eacf331f0ffc35d4b482f1d15a887d3b
